### PR TITLE
Added ML Algorithms - Linear Regression

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
# Description

Added Linear Regression, Machine Learning Algorithm
Fixes a part of #3 

## Type of change

- [x] Added Algorithm
- [x] Folder Structure

# Added to SUMMARY.md (delete section if not needed)?

Have you added the page to SUMMARY.md if this is a new page and not a fix?

- [x] Yes

### CODE REVIEW

**Review by sadn1ck — APPROVED** [review]
LGTM

**Comment by sadn1ck** [comment]
@allcontributors add @Siddhant-K-code  for contributing to documentation

**Comment by Siddhant-K-code** [comment]
In This:
image
`Regression` is referring to a weird link, pls check the final build.

**Comment by sadn1ck** [comment]
Ah thanks, probably messed up the relative links. I'll have a look.

**Pull request merged**
